### ISSUE TITLE
Вёрстка кнопок установщика

### ISSUE THREAD

**Issue by Baziak** [ZFury/ZFury#3]
![e2a30cffa3](https://cloud.githubusercontent.com/assets/241709/5961863/25454944-a7e8-11e4-85b7-2017be21ea95.jpg)

Иконки не отцентрированы по вертикали (firefox, os x).

**Comment by kazimirchuk** [comment]
Baziak, thank you for you issue. Here is a commit https://github.com/ZFury/ZFury/commit/c0af8abb1d05b12afcb34b10885138acfea5ad4f where i fixed that.  These changes will be included in the upcoming release 1.4.3.
